CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(150) NOT NULL,
    login       VARCHAR(80)  NOT NULL,
    senha_hash  VARCHAR(255) NOT NULL,
    token       VARCHAR(500),
    email       VARCHAR(150) NOT NULL,
    endereco    VARCHAR(255),
    cidade      VARCHAR(100),
    estado      CHAR(2),
    telefone    VARCHAR(20),

    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuarios_login UNIQUE (login),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);
