ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS imagem_url VARCHAR(500);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS data_cadastro TIMESTAMP;
UPDATE usuarios SET data_cadastro = CURRENT_TIMESTAMP WHERE data_cadastro IS NULL;
ALTER TABLE usuarios ALTER COLUMN data_cadastro SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ALTER COLUMN data_cadastro SET NOT NULL;
