-- Idempotente: não falha se a tabela já foi criada manualmente no banco.
CREATE TABLE IF NOT EXISTS empresas (
    cod_empresa     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    razao_social    VARCHAR(200) NOT NULL,
    nome_fantasia   VARCHAR(150) NOT NULL,
    cnpj            VARCHAR(18)  NOT NULL,
    email           VARCHAR(150),
    telefone        VARCHAR(20),
    endereco        VARCHAR(255),
    numero          VARCHAR(20),
    bairro          VARCHAR(100),
    cidade          VARCHAR(100),
    estado          CHAR(2),
    cep             VARCHAR(10),
    ativo           CHAR(1) DEFAULT 'S' NOT NULL,
    data_cadastro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_empresas PRIMARY KEY (cod_empresa),
    CONSTRAINT uk_empresas_cnpj UNIQUE (cnpj),
    CONSTRAINT ck_empresas_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE INDEX IF NOT EXISTS idx_empresas_razao_social ON empresas (LOWER(razao_social));
