CREATE TABLE IF NOT EXISTS emissao_etiquetas (
    id_emissao          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa_origem  INTEGER NOT NULL,
    cod_empresa_destino INTEGER NOT NULL,
    numero_pedido       VARCHAR(50) NOT NULL,
    data_pedido         DATE NOT NULL,
    quantidade_volumes  INTEGER NOT NULL,
    status              VARCHAR(30) DEFAULT 'EMITIDA' NOT NULL,
    data_emissao        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_emissao_etiquetas PRIMARY KEY (id_emissao),
    CONSTRAINT fk_emissao_empresa_origem
        FOREIGN KEY (cod_empresa_origem) REFERENCES empresas(cod_empresa),
    CONSTRAINT fk_emissao_empresa_destino
        FOREIGN KEY (cod_empresa_destino) REFERENCES empresas(cod_empresa),
    CONSTRAINT ck_emissao_qtde_volumes CHECK (quantidade_volumes > 0),
    CONSTRAINT ck_emissao_status CHECK (
        status IN ('EMITIDA', 'CANCELADA', 'FINALIZADA')
    )
);
