CREATE TABLE IF NOT EXISTS emissao_etiqueta_volumes (
    id_volume        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_emissao       INTEGER NOT NULL,
    numero_volume    INTEGER NOT NULL,
    codigo_etiqueta  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_emissao_etiqueta_volumes PRIMARY KEY (id_volume),
    CONSTRAINT fk_volume_emissao
        FOREIGN KEY (id_emissao) REFERENCES emissao_etiquetas(id_emissao) ON DELETE CASCADE,
    CONSTRAINT uq_volume_emissao_numero UNIQUE (id_emissao, numero_volume),
    CONSTRAINT uq_volume_codigo_etiqueta UNIQUE (codigo_etiqueta),
    CONSTRAINT ck_volume_numero CHECK (numero_volume > 0)
);

CREATE INDEX IF NOT EXISTS ix_volume_emissao ON emissao_etiqueta_volumes (id_emissao);
