CREATE TABLE IF NOT EXISTS log_auditoria (
    id_log       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario   INTEGER,
    nome         VARCHAR(150),
    email        VARCHAR(150),
    metodo       VARCHAR(10)  NOT NULL,
    rota         VARCHAR(500) NOT NULL,
    acao         VARCHAR(500) NOT NULL,
    ip           VARCHAR(64),
    criado_em    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_log_auditoria PRIMARY KEY (id_log),
    CONSTRAINT fk_log_auditoria_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_log_auditoria_criado_em ON log_auditoria (criado_em DESC);
