-- Tabela de auditoria (também aplicada pelo Flyway V8__log_auditoria.sql)
-- Retenção: registros com mais de 1 hora são apagados automaticamente pelo backend.

CREATE TABLE IF NOT EXISTS log_auditoria (
    id_log       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario   INTEGER,
    nome         VARCHAR(150),
    email        VARCHAR(150),
    metodo       VARCHAR(10)  NOT NULL,
    rota         VARCHAR(500) NOT NULL,
    acao         VARCHAR(500) NOT NULL,
    ip           VARCHAR(64),
    criado_em    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_log_auditoria PRIMARY KEY (id_log),
    CONSTRAINT fk_log_auditoria_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_log_auditoria_criado_em ON log_auditoria (criado_em DESC);

-- Consultar logs da última hora (exemplo)
-- SELECT * FROM log_auditoria WHERE criado_em >= NOW() - INTERVAL '1 hour' ORDER BY criado_em DESC;

-- Se estiver vazio após usar o sistema:
-- 1) Confira o MESMO banco que o backend usa (Render ≠ localhost).
-- 2) No Render → Logs, procure "Auditoria de API ativa" ou "Falha ao gravar log de auditoria".
-- 3) Flyway V8__log_auditoria.sql deve estar aplicada (tabela existe).
-- 4) API admin: GET /api/auditoria/logs com Bearer token de usuário ADMIN.
